#!/bin/bash

# Requirement:
# - Typescript compiler: tsc
# - github.com/go-bindata/go-bindata/
# - https://github.com/tdewolff/minify/
# - date
# - git

cd web/ts/
tsc --outFile /dev/stdout | minify --type=js > ../app.js
cd ../..

go-bindata -pkg=webData -o web/webData/data.go web/{index.html,style.css,*.js}

mkdir -p meta
echo '// Code generated by gen.bash DO NOT EDIT.

package meta

const (
	Date = "'`date -u -I`'"
	Git  = "'`git rev-parse HEAD`'"
)' > meta/meta.go
