// BSD 3-Clause License in LICENSE file at the project root.
// Copyright (c) 2020, Hugues GUILLEUS
// All rights reserved.

package minecraftColor

import (
	"image/color"
	"strings"
)

// Get the color index in the BlockPalette from his name. Return 0 if not found.
func BlocColorIndex(n string) uint8 {
	return BlocColorList[strings.TrimPrefix(n, "minecraft:")]
}

var BlockPalette = color.Palette{
	color.RGBA{},                   // 0 = unknown or background
	color.RGBA{127, 178, 56, 255},  // 1 GRASS
	color.RGBA{247, 233, 163, 255}, // 2 SAND
	color.RGBA{199, 199, 199, 255}, // 3 WOOL
	color.RGBA{255, 0, 0, 255},     // 4 FIRE
	color.RGBA{160, 160, 255, 255}, // 5 ICE
	color.RGBA{160, 160, 255, 255}, // 6 METAL
	color.RGBA{0, 124, 0, 255},     // 7 PLANT
	color.RGBA{255, 255, 255, 255}, // 8 SNOW
	color.RGBA{164, 168, 184, 255}, // 9 CLAY
	color.RGBA{151, 109, 77, 255},  // 10 DIRT
	color.RGBA{112, 112, 112, 255}, // 11 STONE
	color.RGBA{64, 64, 255, 255},   // 12 WATER
	color.RGBA{143, 119, 72, 255},  // 13 WOOD
	color.RGBA{255, 252, 245, 255}, // 14 QUARTZ
	color.RGBA{216, 127, 51, 255},  // 15 COLOR_ORANGE
	color.RGBA{178, 76, 216, 255},  // 16 COLOR_MAGENTA
	color.RGBA{102, 153, 216, 255}, // 17 COLOR_LIGHT_BLUE
	color.RGBA{229, 229, 51, 255},  // 18 COLOR_YELLOW
	color.RGBA{127, 204, 25, 255},  // 19 COLOR_LIGHT_GREEN
	color.RGBA{242, 127, 165, 255}, // 20 COLOR_PINK
	color.RGBA{76, 76, 76, 255},    // 21 COLOR_GRAY
	color.RGBA{153, 153, 153, 255}, // 22 COLOR_LIGHT_GRAY
	color.RGBA{76, 127, 153, 255},  // 23 COLOR_CYAN
	color.RGBA{},                   // 24
	color.RGBA{51, 76, 178, 255},   // 25 COLOR_BLUE
	color.RGBA{102, 76, 51, 255},   // 26 COLOR_BROWN
	color.RGBA{},                   // 27
	color.RGBA{153, 51, 51, 255},   // 28 COLOR_RED
	color.RGBA{25, 25, 25, 255},    // 29 COLOR_BLACK
	color.RGBA{250, 238, 77, 255},  // 30 GOLD
	color.RGBA{92, 219, 213, 255},  // 31 DIAMOND
	color.RGBA{74, 128, 255, 255},  // 32 LAPIS
	color.RGBA{0, 217, 58, 255},    // 33 EMERALD
	color.RGBA{129, 86, 49, 255},   // 34 PODZOL
	color.RGBA{112, 2, 0, 255},     // 35 NETHER
	color.RGBA{209, 177, 161, 255}, // 36 TERRACOTTA_WHITE
	color.RGBA{159, 82, 36, 255},   // 37 TERRACOTTA_ORANGE
	color.RGBA{149, 87, 108, 255},  // 38 TERRACOTTA_MAGENTA
	color.RGBA{112, 108, 138, 255}, // 39 TERRACOTTA_LIGHT_BLUE
	color.RGBA{186, 133, 36, 255},  // 40 TERRACOTTA_YELLOW
	color.RGBA{103, 117, 53, 255},  // 41 TERRACOTTA_LIGHT_GREEN
	color.RGBA{160, 77, 78, 255},   // 42 TERRACOTTA_PINK
	color.RGBA{57, 41, 35, 255},    // 43 TERRACOTTA_GRAY
	color.RGBA{135, 107, 98, 255},  // 44 TERRACOTTA_LIGHT_GRAY
	color.RGBA{87, 92, 92, 255},    // 45 TERRACOTTA_CYAN
	color.RGBA{122, 73, 88, 255},   // 46 TERRACOTTA_PURPLE
	color.RGBA{76, 62, 92, 255},    // 47 TERRACOTTA_BLUE
	color.RGBA{76, 50, 35, 255},    // 48 TERRACOTTA_BROWN
	color.RGBA{76, 82, 42, 255},    // 49 TERRACOTTA_GREEN
	color.RGBA{142, 60, 46, 255},   // 50 TERRACOTTA_RED
	color.RGBA{37, 22, 16, 255},    // 51 TERRACOTTA_BLACK
}

// Source:
// 	https://minecraft.gamepedia.com/Map_item_format#Base_colors
// 	https://minecraft.gamepedia.com/index.php?title=Java_Edition_data_values/Blocks
var BlocColorList = map[string]uint8{
	// 1 GRASS
	"grass_block": 1,
	"slime_block": 1,
	// 2 SAND
	"birch_door":              2,
	"birch_fence_gate":        2,
	"birch_fence":             2,
	"birch_log":               2,
	"birch_planks":            2,
	"birch_pressure_plate":    2,
	"birch_sign":              2,
	"birch_slab":              2,
	"birch_stairs":            2,
	"birch_trapdoor":          2,
	"birch_wood":              2,
	"bone_block":              2,
	"chiseled_sandstone":      2,
	"cut_sandstone_slab":      2,
	"cut_sandstone":           2,
	"end_stone_brick_slab":    2,
	"end_stone_brick_stairs":  2,
	"end_stone_brick_wall":    2,
	"end_stone_bricks":        2,
	"end_stone":               2,
	"glowstone":               2,
	"sand":                    2,
	"sandstone_slab":          2,
	"sandstone_stairs":        2,
	"sandstone_wall":          2,
	"sandstone":               2,
	"scaffolding":             2,
	"smooth_sandstone_slab":   2,
	"smooth_sandstone_stairs": 2,
	"smooth_sandstone":        2,
	"stripped_birch_log":      2,
	"stripped_birch_wood":     2,
	"turtle_egg":              2,
	// 3 WOOL
	"bed":           3,
	"cobweb":        3,
	"mushroom_stem": 3,
	// 4 FIRE
	"fire":           4,
	"flowing_lava":   4,
	"lava":           4,
	"redstone_block": 4,
	"tnt":            4,
	// 5 ICE
	"blue_ice":    5,
	"frosted_ice": 5,
	"ice":         5,
	"packed_ice":  5,
	// 6 METAL
	"anvil":                         6,
	"brewing_stand":                 6,
	"chipped_anvil":                 6,
	"damaged_anvil":                 6,
	"grindstone":                    6,
	"heavy_weighted_pressure_plate": 6,
	"iron_block":                    6,
	"iron_door":                     6,
	"iron_trapdoor":                 6,
	"lantern":                       6,
	"soul_lantern":                  6,
	// 7 PLANT
	"acacia_leaves":         7,
	"acacia_sapling":        7,
	"allium":                7,
	"attached_melon_stem":   7,
	"attached_pumpkin_stem": 7,
	"azure_bluet":           7,
	"bamboo":                7,
	"beetroots":             7,
	"birch_leaves":          7,
	"birch_sapling":         7,
	"blue_orchid":           7,
	"brown_mushroom":        7,
	"cactus":                7,
	"carrots":               7,
	"cocoa":                 7,
	"cornflower":            7,
	"crimson_fungus":        7,
	"dandelion":             7,
	"dark_oak_leaves":       7,
	"dark_oak_sapling":      7,
	"fern":                  7,
	"grass":                 7,
	"jungle_leaves":         7,
	"jungle_sapling":        7,
	"large_fern":            7,
	"lilac":                 7,
	"lily_of_the_valley":    7,
	"lily_pad":              7,
	"melon_seeds":           7,
	"melon_stem":            7,
	"oak_leaves":            7,
	"oak_sapling":           7,
	"orange_tulip":          7,
	"oxeye_daisy":           7,
	"peony":                 7,
	"pink_tulip":            7,
	"poppy":                 7,
	"potatoes":              7,
	"pumpkin_seeds":         7,
	"pumpkin_stem":          7,
	"red_mushroom":          7,
	"red_tulip":             7,
	"rose_bush":             7,
	"spruce_leaves":         7,
	"spruce_sapling":        7,
	"sugar_cane":            7,
	"sunflower":             7,
	"sweet_berry_bush":      7,
	"tall_grass":            7,
	"vine":                  7,
	"warped_fungus":         7,
	"weeping_vines_plant":   7,
	"weeping_vines":         7,
	"wheat_seeds":           7,
	"wheat":                 7,
	"white_tulip":           7,
	"wither_rose":           7,
	// 8 SNOW
	"snow_block":               8,
	"snow":                     8,
	"white_banner":             8,
	"white_bed":                8,
	"white_carpet":             8,
	"white_concrete_powder":    8,
	"white_concrete":           8,
	"white_glazed_terracotta":  8,
	"white_shulker_box":        8,
	"white_stained_glass_pane": 8,
	"white_stained_glass":      8,
	"white_wall_banner":        8,
	"white_wool":               8,
	// 9 CLAY
	"clay":                           9,
	"infested_chiseled_stone_bricks": 9,
	"infested_cobblestone":           9,
	"infested_cracked_stone_bricks":  9,
	"infested_mossy_stone_bricks":    9,
	"infested_stone_bricks":          9,
	"infested_stone":                 9,
	// 10 DIRT
	"brown_mushroom_block":    10,
	"coarse_dirt":             10,
	"dirt":                    10,
	"farmland":                10,
	"granite_slab":            10,
	"granite_stairs":          10,
	"granite_wall":            10,
	"granite":                 10,
	"grass_path":              10,
	"jukebox":                 10,
	"jungle_door":             10,
	"jungle_fence_gate":       10,
	"jungle_fence":            10,
	"jungle_log":              10,
	"jungle_planks":           10,
	"jungle_pressure_plate":   10,
	"jungle_sign":             10,
	"jungle_slab":             10,
	"jungle_stairs":           10,
	"jungle_trapdoor":         10,
	"jungle_wood":             10,
	"polished_granite_slab":   10,
	"polished_granite_stairs": 10,
	"polished_granite":        10,
	"stripped_jungle_log":     10,
	"stripped_jungle_wood":    10,
	// 11 STONE
	"andesite_slab":            11,
	"andesite_stairs":          11,
	"andesite_wall":            11,
	"andesite":                 11,
	"bedrock":                  11,
	"blast_furnace":            11,
	"cauldron":                 11,
	"chiseled_stone_bricks":    11,
	"coal_ore":                 11,
	"cobblestone_slab":         11,
	"cobblestone_stairs":       11,
	"cobblestone_wall":         11,
	"cobblestone":              11,
	"cracked_stone_bricks":     11,
	"diamond_ore":              11,
	"dispenser":                11,
	"dropper":                  11,
	"emerald_ore":              11,
	"ender_chest":              11,
	"furnace":                  11,
	"gold_ore":                 11,
	"gravel":                   11,
	"hopper":                   11,
	"iron_ore":                 11,
	"lapis_ore":                11,
	"mossy_cobblestone_slab":   11,
	"mossy_cobblestone_stairs": 11,
	"mossy_cobblestone_wall":   11,
	"mossy_cobblestone":        11,
	"moving_piston":            11,
	"observer":                 11,
	"piston_head":              11,
	"piston":                   11,
	"polished_andesite_slab":   11,
	"polished_andesite_stairs": 11,
	"polished_andesite":        11,
	"redstone_ore":             11,
	"smoker":                   11,
	"smooth_stone_slab":        11,
	"smooth_stone":             11,
	"spawner":                  11,
	"sticky_piston":            11,
	"stone_brick_slab":         11,
	"stone_brick_stairs":       11,
	"stone_brick_wall":         11,
	"stone_bricks":             11,
	"stone_pressure_plate":     11,
	"stone_slab":               11,
	"stone_stairs":             11,
	"stone":                    11,
	"stonecutter":              11,
	// 12 WATER
	"bubble_column": 12,
	"flowing_water": 12,
	"kelp_plant":    12,
	"kelp":          12,
	"seagrass":      12,
	"tall_seagrass": 12,
	"water":         12,
	// 13 WOOD
	"bamboo_sapling":     13,
	"barrel":             13,
	"bee_nest":           13,
	"beehive":            13,
	"bookshelf":          13,
	"cartography_table":  13,
	"chest":              13,
	"composter":          13,
	"crafting_table":     13,
	"daylight_detector":  13,
	"dead_bush":          13,
	"fletching_table":    13,
	"lectern":            13,
	"loom":               13,
	"note_block":         13,
	"oak_door":           13,
	"oak_fence_gate":     13,
	"oak_fence":          13,
	"oak_log":            13,
	"oak_planks":         13,
	"oak_pressure_plate": 13,
	"oak_sign":           13,
	"oak_slab":           13,
	"oak_stairs":         13,
	"oak_trapdoor":       13,
	"oak_wood":           13,
	"petrified_oak_slab": 13,
	"smithing_table":     13,
	"stripped_oak_log":   13,
	"stripped_oak_wood":  13,
	"trapped_chest":      13,
	// 14 QUARTZ
	"chiseled_quartz_block":   14,
	"diorite_slab":            14,
	"diorite_stairs":          14,
	"diorite_wall":            14,
	"diorite":                 14,
	"polished_diorite_slab":   14,
	"polished_diorite_stairs": 14,
	"polished_diorite":        14,
	"quartz_block":            14,
	"quartz_pillar":           14,
	"quartz_slab":             14,
	"quartz_stairs":           14,
	"sea_lantern":             14,
	"smooth_quartz_slab":      14,
	"smooth_quartz_stairs":    14,
	"smooth_quartz":           14,
	"target":                  14,
	// 15 COLOR_ORANGE
	"chiseled_red_sandstone": 15,
	"cut_red_sandstone":      15,
	"red_sand":               15,
	"red_sandstone":          15,
	"smooth_red_sandstone":   15,
	// 16 COLOR_MAGENTA
	"magenta_banner":             16,
	"magenta_bed":                16,
	"magenta_carpet":             16,
	"magenta_concrete_powder":    16,
	"magenta_concrete":           16,
	"magenta_glazed_terracotta":  16,
	"magenta_shulker_box":        16,
	"magenta_stained_glass_pane": 16,
	"magenta_stained_glass":      16,
	"magenta_wool":               16,
	"purpur_block":               16,
	"purpur_pillar":              16,
	"purpur_slab":                16,
	"purpur_stairs":              16,
	// 17 COLOR_LIGHT_BLUE
	"light_blue_banner":             17,
	"light_blue_bed":                17,
	"light_blue_carpet":             17,
	"light_blue_concrete_powder":    17,
	"light_blue_concrete":           17,
	"light_blue_glazed_terracotta":  17,
	"light_blue_shulker_box":        17,
	"light_blue_stained_glass_pane": 17,
	"light_blue_stained_glass":      17,
	"light_blue_wool":               17,
	"soul_fire":                     17,
	// 18 COLOR_YELLOW
	"hay_block":                 18,
	"horn_coral_block":          18,
	"horn_coral_fan":            18,
	"horn_coral":                18,
	"sponge":                    18,
	"wet_sponge":                18,
	"yellow_banner":             18,
	"yellow_bed":                18,
	"yellow_carpet":             18,
	"yellow_concrete_powder":    18,
	"yellow_concrete":           18,
	"yellow_glazed_terracotta":  18,
	"yellow_shulker_box":        18,
	"yellow_stained_glass_pane": 18,
	"yellow_stained_glass":      18,
	"yellow_wool":               18,
	// 19 COLOR_LIGHT_GREEN
	"lime_banner":             19,
	"lime_bed":                19,
	"lime_carpet":             19,
	"lime_concrete_powder":    19,
	"lime_concrete":           19,
	"lime_glazed_terracotta":  19,
	"lime_shulker_box":        19,
	"lime_stained_glass_pane": 19,
	"lime_stained_glass":      19,
	"lime_wool":               19,
	"melon":                   19,
	// 20 COLOR_PINK
	"brain_coral_block":       20,
	"brain_coral_fan":         20,
	"brain_coral":             20,
	"pink_banner":             20,
	"pink_bed":                20,
	"pink_carpet":             20,
	"pink_concrete_powder":    20,
	"pink_concrete":           20,
	"pink_glazed_terracotta":  20,
	"pink_shulker_box":        20,
	"pink_stained_glass_pane": 20,
	"pink_stained_glass":      20,
	"pink_wool":               20,
	// 21 COLOR_GRAY
	"dead_brain_coral_block":  21,
	"dead_brain_coral_fan":    21,
	"dead_brain_coral":        21,
	"dead_bubble_coral_block": 21,
	"dead_bubble_coral_fan":   21,
	"dead_bubble_coral":       21,
	"dead_fire_coral_block":   21,
	"dead_fire_coral_fan":     21,
	"dead_fire_coral":         21,
	"dead_horn_coral_block":   21,
	"dead_horn_coral_fan":     21,
	"dead_horn_coral":         21,
	"dead_tube_coral_block":   21,
	"dead_tube_coral_fan":     21,
	"dead_tube_coral":         21,
	"gray_banner":             21,
	"gray_bed":                21,
	"gray_carpet":             21,
	"gray_concrete_powder":    21,
	"gray_concrete":           21,
	"gray_glazed_terracotta":  21,
	"gray_shulker_box":        21,
	"gray_stained_glass_pane": 21,
	"gray_stained_glass":      21,
	"gray_wool":               21,
	"stripped_acacia_wood":    21,
	// 22 COLOR_LIGHT_GRAY
	"jigsaw":                        22,
	"light_gray_banner":             22,
	"light_gray_bed":                22,
	"light_gray_carpet":             22,
	"light_gray_concrete_powder":    22,
	"light_gray_concrete":           22,
	"light_gray_glazed_terracotta":  22,
	"light_gray_shulker_box":        22,
	"light_gray_stained_glass_pane": 22,
	"light_gray_stained_glass":      22,
	"light_gray_wool":               22,
	"structure_block":               22,
	// 23 COLOR_CYAN
	"cyan_banner":             23,
	"cyan_bed":                23,
	"cyan_carpet":             23,
	"cyan_concrete_powder":    23,
	"cyan_concrete":           23,
	"cyan_glazed_terracotta":  23,
	"cyan_shulker_box":        23,
	"cyan_stained_glass_pane": 23,
	"cyan_stained_glass":      23,
	"cyan_wool":               23,
	"nether_sprouts":          23,
	"prismarine_slab":         23,
	"prismarine_stairs":       23,
	"prismarine_wall":         23,
	"prismarine":              23,
	// minecraft 1.16: Warped (Stem, Stripped Stem, Hyphae, Stripped Hyphae, Nylium, Wart Block, Roots, Planks, Slab, Pressure Plate, Fence, Trapdoor, Fence Gate, Stairs, Door, Sign),
	// 24 COLOR_PURPLE
	"bubble_coral_block":        24,
	"bubble_coral_fan":          24,
	"bubble_coral":              24,
	"chorus_flower":             24,
	"chorus_plant":              24,
	"mycelium":                  24,
	"purple_banner":             24,
	"purple_bed":                24,
	"purple_carpet":             24,
	"purple_concrete_powder":    24,
	"purple_concrete":           24,
	"purple_glazed_terracotta":  24,
	"purple_stained_glass_pane": 24,
	"purple_stained_glass":      24,
	"purple_wool":               24,
	"repeating_command_block":   24,
	"shulker_box":               24,
	// 25 COLOR_BLUE
	"blue_banner":             25,
	"blue_bed":                25,
	"blue_carpet":             25,
	"blue_concrete_powder":    25,
	"blue_concrete":           25,
	"blue_glazed_terracotta":  25,
	"blue_shulker_box":        25,
	"blue_stained_glass_pane": 25,
	"blue_stained_glass":      25,
	"blue_wool":               25,
	"tube_coral_block":        25,
	"tube_coral_fan":          25,
	"tube_coral":              25,
	// 26 COLOR_BROWN
	"brown_banner":             26,
	"brown_bed":                26,
	"brown_carpet":             26,
	"brown_concrete_powder":    26,
	"brown_concrete":           26,
	"brown_glazed_terracotta":  26,
	"brown_shulker_box":        26,
	"brown_stained_glass_pane": 26,
	"brown_stained_glass":      26,
	"brown_wool":               26,
	"command_block":            26,
	"dark_oak_door":            26,
	"dark_oak_fence_gate":      26,
	"dark_oak_fence":           26,
	"dark_oak_log":             26,
	"dark_oak_planks":          26,
	"dark_oak_pressure_plate":  26,
	"dark_oak_sign":            26,
	"dark_oak_slab":            26,
	"dark_oak_stairs":          26,
	"dark_oak_trapdoor":        26,
	"dark_oak_wood":            26,
	"soul_sand":                26,
	"soul_soil":                26,
	"stripped_dark_oak_log":    26,
	// Brown Mushroom‌[upcoming: JE 1.16] ????
	// 27 COLOR_GREEN
	"chain_command_block":      26,
	"dried_kelp_block":         26,
	"end_portal_frame":         26,
	"green_banner":             26,
	"green_bed":                26,
	"green_carpet":             26,
	"green_concrete_powder":    26,
	"green_concrete":           26,
	"green_glazed_terracotta":  26,
	"green_shulker_box":        26,
	"green_stained_glass_pane": 26,
	"green_stained_glass":      26,
	"green_wool":               26,
	"sea_pickle":               26,
	// 28 COLOR_RED
	"brick_slab":             28,
	"brick_stairs":           28,
	"brick_wall":             28,
	"bricks":                 28,
	"enchanting_table":       28,
	"fire_coral_block":       28,
	"fire_coral_fan":         28,
	"fire_coral":             28,
	"nether_wart_block":      28,
	"nether_wart":            28,
	"red_banner":             28,
	"red_bed":                28,
	"red_carpet":             28,
	"red_concrete_powder":    28,
	"red_concrete":           28,
	"red_glazed_terracotta":  28,
	"red_shulker_box":        28,
	"red_stained_glass_pane": 28,
	"red_stained_glass":      28,
	"red_wool":               28,
	// Red Mushroom Block,
	// Red Mushroom,‌
	// [upcoming: JE 1.16] Crimson (Stem, Stripped Stem, Hyphae, Stripped Hyphae, Nylium), Shroomlight
	// 29 COLOR_BLACK
	"ancient_debris":           29,
	"basalt":                   29,
	"black_banner":             29,
	"black_bed":                29,
	"black_carpet":             29,
	"black_concrete_powder":    29,
	"black_concrete":           29,
	"black_glazed_terracotta":  29,
	"black_shulker_box":        29,
	"black_stained_glass_pane": 29,
	"black_stained_glass":      29,
	"black_wall_banner":        29,
	"black_wool":               29,
	"coal_block":               29,
	"crying_obsidian":          29,
	"dragon_egg":               29,
	"end_gateway":              29,
	"end_portal":               29,
	"netherite_block":          29,
	"obsidian":                 29,
	"polished_basalt":          29, // minecraft 1.16 ???
	// 30 GOLD
	"bell":                          30,
	"gold_block":                    30,
	"light_weighted_pressure_plate": 30,
	// 31 DIAMOND
	"beacon":                  31,
	"conduit":                 31,
	"dark_prismarine_slab":    31,
	"dark_prismarine_stairs":  31,
	"dark_prismarine":         31,
	"diamond_block":           31,
	"prismarine_brick_slab":   31,
	"prismarine_brick_stairs": 31,
	"prismarine_bricks":       31,
	// 32 LAPIS
	"lapis_block": 32,
	// 33 EMERALD
	"emerald_block": 33,
	// 34 PODZOL
	"campfire":              34,
	"podzol":                34,
	"spruce_door":           34,
	"spruce_fence_gate":     34,
	"spruce_fence":          34,
	"spruce_log":            34,
	"spruce_planks":         34,
	"spruce_pressure_plate": 34,
	"spruce_sign":           34,
	"spruce_slab":           34,
	"spruce_stairs":         34,
	"spruce_trapdoor":       34,
	"spruce_wood":           34,
	"stripped_spruce_log":   34,
	"stripped_spruce_wood":  34,
	// 35 NETHER
	"magma_block":             35,
	"nether_brick_fence":      35,
	"nether_brick_slab":       35,
	"nether_brick_stairs":     35,
	"nether_brick_wall":       35,
	"nether_bricks":           35,
	"nether_quartz_ore":       35,
	"netherrack":              35,
	"red_nether_brick_slab":   35,
	"red_nether_brick_stairs": 35,
	"red_nether_brick_wall":   35,
	"red_nether_bricks":       35,
	// minecraft 1.16: Crimson (Roots, Planks, Slab, Pressure Plate, Fence, Trapdoor, Fence Gate, Stairs, Door, Sign)
	// 36 TERRACOTTA_WHITE
	"white_terracotta": 36,
	// 37 TERRACOTTA_ORANGE
	"orange_terracotta": 37,
	// 38 TERRACOTTA_MAGENTA
	"magenta_terracotta": 38,
	// 39 TERRACOTTA_LIGHT_BLUE
	"light_blue_terracotta": 39,
	// 40 TERRACOTTA_YELLOW
	"yellow_terracotta": 40,
	// 41 TERRACOTTA_LIGHT_GREEN
	"lime_terracotta": 41,
	// 42 TERRACOTTA_PINK
	"pink_terracotta": 42,
	// 43 TERRACOTTA_GRAY
	"gray_terracotta": 43,
	// 44 TERRACOTTA_LIGHT_GRAY
	"light_gray_terracotta": 44,
	// 45 TERRACOTTA_CYAN
	"cyan_terracotta": 45,
	// 46 TERRACOTTA_PURPLE
	"purple_shulker_box": 46,
	"purple_terracotta":  46,
	// 47 TERRACOTTA_BLUE
	"blue_terracotta": 47,
	// 48 TERRACOTTA_BROWN
	"brown_terracotta": 48,
	// 49 TERRACOTTA_GREEN
	"green_terracotta": 49,
	// 50 TERRACOTTA_RED
	"red_terracotta": 50,
	// 51 TERRACOTTA_BLACK
	"black_terracotta": 51,
}
